//@ui5-bundle net/php/fiori/persons/persons/Component-preload.js
jQuery.sap.registerPreloadedModules({
"version":"2.0",
"modules":{
	"net/php/fiori/persons/persons/Component.js":function(){sap.ui.define(["sap/fe/core/AppComponent"],function(e){"use strict";return e.extend("net.php.fiori.persons.persons.Component",{metadata:{manifest:"json"}})});
},
	"net/php/fiori/persons/persons/i18n/i18n.properties":'# This is the resource bundle for persons\n\n#Texts for manifest.json\n\n#XTIT: Application name\nappTitle=Fiori persons example\n\n#YDES: Application description\nappDescription=Fiori Elements example\n',
	"net/php/fiori/persons/persons/manifest.json":'{"_version":"1.32.0","sap.app":{"id":"net.php.fiori.persons.persons","type":"application","i18n":"i18n/i18n.properties","applicationVersion":{"version":"1.0.0"},"title":"{{appTitle}}","description":"{{appDescription}}","dataSources":{"mainService":{"uri":"/odata/","type":"OData","settings":{"annotations":["annotation"],"odataVersion":"4.0","localUri":"localService/metadata.xml"}},"annotation":{"type":"ODataAnnotation","uri":"annotations/annotation.xml","settings":{"localUri":"annotations/annotation.xml"}}},"offline":false,"resources":"resources.json","sourceTemplate":{"id":"ui5template.fiorielements.v4.lrop","version":"1.0.0"}},"sap.ui":{"technology":"UI5","icons":{"icon":"","favIcon":"","phone":"","phone@2":"","tablet":"","tablet@2":""},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"resources":{"js":[],"css":[]},"dependencies":{"minUI5Version":"1.109.3","libs":{"sap.ui.core":{},"sap.fe.templates":{}}},"models":{"@i18n":{"type":"sap.ui.model.resource.ResourceModel","uri":"i18n/i18n.properties"},"i18n":{"type":"sap.ui.model.resource.ResourceModel","uri":"i18n/i18n.properties"},"":{"dataSource":"mainService","preload":true,"settings":{"synchronizationMode":"None","operationMode":"Server","autoExpandSelect":true,"earlyRequests":true}}},"routing":{"routes":[{"pattern":":?query:","name":"personsList","target":"personsList"},{"pattern":"persons({key}):?query:","name":"personsObjectPage","target":"personsObjectPage"}],"targets":{"personsList":{"type":"Component","id":"personsList","name":"sap.fe.templates.ListReport","options":{"settings":{"entitySet":"persons","variantManagement":"Page","navigation":{"persons":{"detail":{"route":"personsObjectPage"}}}}}},"personsObjectPage":{"type":"Component","id":"personsObjectPage","name":"sap.fe.templates.ObjectPage","options":{"settings":{"editableHeaderContent":false,"entitySet":"persons"}}}}},"contentDensities":{"compact":true,"cozy":true}},"sap.platform.abap":{"_version":"1.1.0","uri":""},"sap.platform.hcp":{"_version":"1.1.0","uri":""},"sap.fiori":{"_version":"1.1.0","registrationIds":[],"archeType":"transactional"}}'
}});
