//@ui5-bundle net/php/launchpad/launchpad/Component-preload.js
jQuery.sap.registerPreloadedModules({
"version":"2.0",
"modules":{
	"net/php/launchpad/launchpad/Component.js":function(){sap.ui.define(["sap/ui/core/UIComponent","sap/ui/Device","net/php/launchpad/launchpad/model/models"],function(e,t,i){"use strict";return e.extend("net.php.launchpad.launchpad.Component",{metadata:{manifest:"json"},init:function(){e.prototype.init.apply(this,arguments);this.getRouter().initialize();this.setModel(i.createDeviceModel(),"device")}})});
},
	"net/php/launchpad/launchpad/controller/launchpad.controller.js":function(){sap.ui.define(["sap/ui/core/mvc/Controller"],function(n){"use strict";return n.extend("net.php.launchpad.launchpad.controller.launchpad",{onInit:function(){},onUserPress:function(){alert("Hello World")}})});
},
	"net/php/launchpad/launchpad/i18n/i18n.properties":'# This is the resource bundle for net.php.launchpad.launchpad\n\n#Texts for manifest.json\n\n#XTIT: Application name\nappTitle=Fiori launchpad\n\n#YDES: Application description\nappDescription=Fiori launchpad\n#XTIT: Main view title\ntitle=Fiori launchpad',
	"net/php/launchpad/launchpad/manifest.json":'{"_version":"1.32.0","sap.app":{"id":"net.php.launchpad.launchpad","type":"application","i18n":"i18n/i18n.properties","applicationVersion":{"version":"0.0.1"},"title":"{{appTitle}}","description":"{{appDescription}}","dataSources":{}},"sap.ui":{"technology":"UI5","icons":{},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"flexEnabled":true,"dependencies":{"minUI5Version":"1.109.3","libs":{"sap.ui.core":{}}},"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"net.php.launchpad.launchpad.i18n.i18n"}},"":{"dataSource":"mainService","preload":true,"settings":{"synchronizationMode":"None","operationMode":"Server","autoExpandSelect":true,"earlyRequests":true,"groupId":"$direct"}}},"resources":{"css":[]},"routing":{"config":{"routerClass":"sap.m.routing.Router","viewType":"XML","async":true,"viewPath":"net.php.launchpad.launchpad.view","controlAggregation":"pages","controlId":"app","clearControlAggregation":false},"routes":[{"name":"Routelaunchpad","pattern":"Routelaunchpad","target":["Targetlaunchpad"]}],"targets":{"Targetlaunchpad":{"viewType":"XML","transition":"slide","clearControlAggregation":false,"viewId":"launchpad","viewName":"launchpad"}}},"rootView":{"viewName":"net.php.launchpad.launchpad.view.launchpad","type":"XML","async":true,"id":"launchpad"}}}',
	"net/php/launchpad/launchpad/model/models.js":function(){sap.ui.define(["sap/ui/model/json/JSONModel","sap/ui/Device"],function(e,n){"use strict";return{createDeviceModel:function(){var i=new e(n);i.setDefaultBindingMode("OneWay");return i}}});
},
	"net/php/launchpad/launchpad/view/launchpad.view.xml":'<mvc:View\n    controllerName="net.php.launchpad.launchpad.controller.launchpad"\n    xmlns="sap.m"\n    xmlns:mvc="sap.ui.core.mvc"\n    xmlns:tnt="sap.tnt"\n    displayBlock="true"\n><tnt:ToolHeader><Image src="/resources/logo.png" height="70%" /><ToolbarSpacer /><Button icon="sap-icon://bell" type="Transparent" /><Button icon="sap-icon://person-placeholder" type="Transparent" press=".onUserPress" /></tnt:ToolHeader></mvc:View>\n'
}});
