//@ui5-bundle net/php/flights/flights/Component-preload.js
sap.ui.require.preload({
	"net/php/flights/flights/Component.js":function(){
sap.ui.define(["sap/ui/core/UIComponent","sap/ui/Device","net/php/flights/flights/model/models"],function(e,t,i){"use strict";return e.extend("net.php.flights.flights.Component",{metadata:{manifest:"json"},init:function(){e.prototype.init.apply(this,arguments);this.getRouter().initialize();this.setModel(i.createDeviceModel(),"device")}})});
},
	"net/php/flights/flights/controller/flights.controller.js":function(){
sap.ui.define(["sap/ui/core/mvc/Controller"],function(n){"use strict";return n.extend("net.php.flights.flights.controller.flights",{onInit:function(){},onUserPress:function(){alert("Hello World")}})});
},
	"net/php/flights/flights/i18n/i18n.properties":'# This is the resource bundle for net.php.flights.flights\n\n#Texts for manifest.json\n\n#XTIT: Application name\nappTitle=Flights example\n\n#YDES: Application description\nappDescription=Flights example\n#XTIT: Main view title\ntitle=Flights example',
	"net/php/flights/flights/manifest.json":'{"_version":"1.32.0","sap.app":{"id":"net.php.flights.flights","type":"application","i18n":"i18n/i18n.properties","applicationVersion":{"version":"0.0.1"},"title":"{{appTitle}}","description":"{{appDescription}}","dataSources":{}},"sap.ui":{"technology":"UI5","icons":{},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"flexEnabled":true,"dependencies":{"minUI5Version":"1.109.3","libs":{"sap.ui.core":{}}},"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"net.php.flights.flights.i18n.i18n"}},"":{"dataSource":"mainService","preload":true,"settings":{"synchronizationMode":"None","operationMode":"Server","autoExpandSelect":true,"earlyRequests":true,"groupId":"$direct"}}},"resources":{"css":[]},"routing":{"config":{"routerClass":"sap.m.routing.Router","viewType":"XML","async":true,"viewPath":"net.php.flights.flights.view","controlAggregation":"pages","controlId":"app","clearControlAggregation":false},"routes":[{"name":"Routelaunchpad","pattern":"Routelaunchpad","target":["Targetlaunchpad"]}],"targets":{"Targetlaunchpad":{"viewType":"XML","transition":"slide","clearControlAggregation":false,"viewId":"launchpad","viewName":"launchpad"}}},"rootView":{"viewName":"net.php.flights.flights.view.flights","type":"XML","async":true,"id":"launchpad"}}}',
	"net/php/flights/flights/model/models.js":function(){
sap.ui.define(["sap/ui/model/json/JSONModel","sap/ui/Device"],function(e,n){"use strict";return{createDeviceModel:function(){var i=new e(n);i.setDefaultBindingMode("OneWay");return i}}});
},
	"net/php/flights/flights/view/flights.view.xml":'<mvc:View\n        xmlns="sap.m"\n        xmlns:mvc="sap.ui.core.mvc"><VBox class="sapUiSmallMargin"><Text text="Lorem ipsum dolor st amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores e\nt ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam er\nat, sed diam voluptua. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat" /></VBox></mvc:View>\n'
});
//# sourceMappingURL=Component-preload.js.map
